name: Simple CI/CD Pipeline for CSE 270

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-mock
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Make lint non-blocking but keep the warnings summary line
      - name: Lint with flake8 (non-blocking)
        run: |
          set +e
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          FLK_STRICT=$?
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          exit 0

      - name: Run tests
        run: |
          pytest -q || true  # keep non-blocking if no tests present

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: teton/1.6

  deploy:
    name: Deploy to GitHub Pages
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

